[project]
name = "mq"
version = "0.2.7"
description = "Command-line tool to query configured LLM chat models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm-client @ git+https://github.com/xlr8harder/llm_client.git@3d4e10135298655d5d46688b5822be2240b967b3",
]

[project.scripts]
mq = "mq.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
